datasets:
  raw:
    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/sales_data.csv
      driver_params: {}

    social_media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/social_media_data_csv.csv
      driver_params: {}

    google_search:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/google_search_data.csv
      driver_params: {}

    product_manufacturer:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/product_manufacturer_list.csv
      driver_params: {}

    Theme:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/Theme_list.csv
      driver_params: {}

    Theme_product:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/Theme_product_list.csv
      driver_params: {}



  cleaned:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/sales.parquet
      driver_params: {}
      
    social_media:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/social_media_data_csv.parquet
      driver_params: {}

    google_search:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/google_search_data.parquet
      driver_params: {}

    product_manufacturer:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/product_manufacturer_list.parquet
      driver_params: {}

    Theme:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/Theme_list.parquet
      driver_params: {}

    Theme_product:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/Theme_product_list.parquet
      driver_params: {}



  processed:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/sales.parquet
      driver_params: {}
    
    social_media:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/social_media_data_csv.parquet
      driver_params: {}

    google_search:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/google_search_data.parquet
      driver_params: {}

    product_manufacturer:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/product_manufacturer_list.parquet
      driver_params: {}

    Theme:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/Theme_list.parquet
      driver_params: {}

    Theme_product:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/Theme_product_list.parquet
      driver_params: {}




  train:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/target.parquet
        driver_params:
          save:
            index: False
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/target.parquet
        driver_params:
          save:
            index: False
  score:
    sales:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/scored_output.parquet
        driver_params:
          save:
            index: False